language: node_js
sudo: required
node_js:
- 8.16.2
branches:
  only:
  - master
before_script:
- npm install
script:
- "./scripts/build-all.sh"
- "./scripts/tar-all.sh"
deploy:
  provider: releases
  api_key:
    secure: oXxGSAuUDt/Q/DY7yyquJf/NQ7xpBpK0pFWzQRHI2xKgTkxaqbhxPuCS7Yupnjq/ugksNIi0A6Di2JEs8qNpkI6TFwXKC+lMusyamqdNv1R42wrbNmbD7GtSws8L+6P5/wCyJPCsAdp7pqFspGPfC3Y9SD/WPtD/+JYX4csUkgXY1thfGhGi1kNgnVemlqwrUQc1nfgNXI75aLuxLWgJ/yFwZtO/aOevxr6XDCNTp4pUW+Pzldp7VEPC91TfE3ScCvJG9v9VIvBWNOlrDM03XfwkhiR+OXFjMa56/RIY4s6NZRBce0A1CSB94EFgQZODq8gTN9RT9Atoe0+ylrOpRX+wzoannvP5TKOEErz3e27WN0MC7Gw7vlw+wmp17ogpcA3NT5FOdU/nb0VlUFkjZYlZW7QqL4Q2tRRuCtWPpU+eYPdrSsKJ6Hyxu48PFSLL87SDPDKfGys4P6fE+S6Ywn8TDpvs3Vn4lPWa8MrySAJIvwqUAM+LU7RU44PrXROlNEdDVqgEFIpxm6U5xZNzNMKjMnIEYA1UWV6zluG67NQjCSfjsufTsYJCqyAqTIFiJKp0EPIXe5q/bg/DRRnAfsGjQO2VRJXtMStYTGrGWQugEk3fHR8NJtG3CtrNS0xg1StyCxNanJrsZEBJggY30pJ1QLCUGB+Nqyuwzj/YNNo=
  file: dist/linux-x64.tar.gz
  skip_cleanup: true
  on:
    repo: palytoxin/electronic-wechat
